const { Schema } = require("mongoose");

const planosSchema = new Schema({
  user_id: { type: Number, required: false, unique: true },
  firstname: { type: String, required: true },
  planoAtivo: { type: Boolean, required: false, default: false },
  diaPlano: { type: Number, required: false, min: 1, max: 81 },
  versiculoPlano: { type: Number, required: false, min: 0, max: 9000 },
  messagePlano: { type: [String], required: false },
  messagePositionPlano: { type: Number, required: false, min: 0, max: 25 },
  messageIdPlano: { type: Number, required: false },
  planosConcluidos: { type: Number, required: false, min: 0, max: 20000 },
  plano1: { type: Boolean, required: false, default: false },
  plano2: { type: Boolean, required: false, default: false },
  plano3: { type: Boolean, required: false, default: false },
  plano4: { type: Boolean, required: false, default: false },
  plano5: { type: Boolean, required: false, default: false },
  plano6: { type: Boolean, required: false, default: false },
  plano7: { type: Boolean, required: false, default: false },
  plano8: { type: Boolean, required: false, default: false },
  plano9: { type: Boolean, required: false, default: false },
  plano10: { type: Boolean, required: false, default: false },
  plano11: { type: Boolean, required: false, default: false },
  plano12: { type: Boolean, required: false, default: false },
  plano13: { type: Boolean, required: false, default: false },
  plano14: { type: Boolean, required: false, default: false },
  plano15: { type: Boolean, required: false, default: false },
  plano16: { type: Boolean, required: false, default: false },
  plano17: { type: Boolean, required: false, default: false },
  plano18: { type: Boolean, required: false, default: false },
  plano19: { type: Boolean, required: false, default: false },
  plano20: { type: Boolean, required: false, default: false },
  plano21: { type: Boolean, required: false, default: false },
  plano22: { type: Boolean, required: false, default: false },
  plano23: { type: Boolean, required: false, default: false },
  plano24: { type: Boolean, required: false, default: false },
  plano25: { type: Boolean, required: false, default: false },
  plano26: { type: Boolean, required: false, default: false },
  plano27: { type: Boolean, required: false, default: false },
  plano28: { type: Boolean, required: false, default: false },
  plano29: { type: Boolean, required: false, default: false },
  plano30: { type: Boolean, required: false, default: false },
});

module.exports = planosSchema;